### ISSUE TITLE
Error: LZFSE is not yet supported

### ISSUE THREAD

**Issue by flylzj** [darlinghq/darling-dmg#93] opened 2019-07-19 04:06 UTC
when i ran `Darling [/Volumes/SystemRoot/home/lzj/Downloads]$ hdiutil attach uu.dmg`
and i got
```
Skipping partition of type Primary GPT Header
Skipping partition of type Primary GPT Table
Skipping partition of type Apple_Free
Using partition #3 of type Apple_HFS
Error: LZFSE is not yet supported

Possible reasons:
1) The file is corrupt.
2) The file is not really a DMG file, although it resembles one.
3) There is a bug in darling-dmg.
```
does this mean the app can't be run by darling

**Comment by ahyattdev** [comment] 2019-07-20 20:48
Duplicate of #88

**Closed by ahyattdev** 2019-07-20 20:48 UTC

**Comment by flylzj** [comment] 2019-07-22 06:13
So, can't I still run this dmg file?

**Comment by ahyattdev** [comment] 2019-07-23 02:32
Yes, I tested using the DMG from #88 and it mounted and I could view the contents

**Comment by flylzj** [comment] 2019-07-23 02:51
Could you tell me how I can mount this [DMG](https://adl.netease.com/d/g/uu/c/uumac?type=pc)?

**Comment by ahyattdev** [comment] 2019-07-24 00:47
@flylzj the same way you would mount it on the command line from macOS, which is `hdiutil attach myfile.dmg` 👍
